# Generated by Django 5.1 on 2025-05-30 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_alter_spotifytoken_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyricAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=100, unique=True)),
                ('track_name', models.CharField(blank=True, max_length=200)),
                ('artist_name', models.CharField(blank=True, max_length=200)),
                ('lyrics', models.TextField()),
                ('emotions', models.JSONField()),
                ('confidence_score', models.FloatField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
            ],
            options={
                'db_table': 'lyric_analysis',
            },
        ),
        migrations.CreateModel(
            name='EmotionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_emotions', models.JSONField()),
                ('feedback_type', models.CharField(choices=[('correction', 'Correction'), ('validation', 'Validation'), ('additional', 'Additional Emotion')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.lyricanalysis')),
            ],
            options={
                'db_table': 'emotion_feedback',
            },
        ),
    ]
